#!/bin/bash

if [ -z "$1" ] 
   then echo "Usage: $0 outputfilename"
        exit
fi

if [ -f "$1" ]
   then echo "removing: $1"
        rm -vf $1
	sync
fi

bs=1024
count=4000000
count=10000000

total=$(( $bs * $count))

echo "writing $total bytes to: $1"
dd if=/dev/zero bs=$bs count=$count of=$1 &
BGPID=$!

trap "kill $BGPID; rm -vf '$1'; exit" INT HUP QUIT TERM EXIT

sleep 5
while ps --no-heading -fp $BGPID >/dev/null 
do kill -USR1 $BGPID
   sleep 5
done

trap "rm -vf '$1'; exit" INT HUP QUIT TERM EXIT

echo "write complete, syncing"
sync
echo "reading from: $1"
dd if=$1 bs=$bs count=$count of=/dev/null
echo "removing: $1"
rm -vf $1
